# Приклад.

#### Використовуючи елементарні перетворення рядків, перетворити матрицю A в верхню трикутну матрицю, де:

![Alt-текст](pics/pic1.png "Picture")

In [10]:
import numpy
A = numpy.array([[4, 2, 0],[1, 3, 2],[-1, 3, 10]])
print(A)

[[ 4  2  0]
 [ 1  3  2]
 [-1  3 10]]


### Розвязок:
#### поміняємо перший та другий рядок місцями


![Alt-текст](pics/pic2.png "Picture")

In [11]:
A1 = numpy.array([A[1],A[0],A[2]])
print(A1)

[[ 1  3  2]
 [ 4  2  0]
 [-1  3 10]]


#### до 2-го рядка додати 1-ший, помножений на -4; до третього рядка додати перший


![Alt-текст](pics/pic3.png "Picture")

In [14]:
A2 = numpy.array([A1[0], A1[1] + A1[0]*(-4), A1[2] + A1[0]])
print(A2)

[[  1   3   2]
 [  0 -10  -8]
 [  0   6  12]]


#### 2-ий рядок поділити на -2, третій рядок ділимо на 6

In [16]:
A3 = numpy.array([A2[0], A2[1] / (-2), A2[2] / 6], dtype=int)
print(A3)

[[1 3 2]
 [0 5 4]
 [0 1 2]]


#### поміняємо другий та третій рядок місцями


![Alt-текст](pics/pic5.png "Picture")

In [17]:
A4 = numpy.array([A3[0],A3[2],A3[1]])
print(A4)

[[1 3 2]
 [0 1 2]
 [0 5 4]]


#### до 3-тього рядка додамо 2-ий, помножений на -5

![Alt-текст](pics/pic6.png "Picture")

In [19]:
A5 = numpy.array([A4[0],A4[1],A4[2] + A4[1]*(-5)])
print(A5)

[[ 1  3  2]
 [ 0  1  2]
 [ 0  0 -6]]
